# https://pre-commit.com/
ci:
    autofix_prs: false
exclude: docs/_static
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black

  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.4
    hooks:
      - id: blackdoc

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
       - id: flake8

  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
       - id: darglint

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        exclude: docs
        additional_dependencies: ["xarray", "types-pkg_resources"]

  - repo: https://github.com/PyCQA/doc8
    rev: 0.11.2
    hooks:
      - id: doc8
